artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_bucket: mlflow-bucket-predictive-maintenance
  source_object_key: raw_data/train_FD004.txt.zip
  local_data_file: artifacts/data_ingestion/train_FD004.txt.zip
  unzip_dir: artifacts/data_ingestion
